# Generated by Django 4.2.2 on 2024-01-02 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_movie_image"),
        ("repertoire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repertoire",
            name="movie_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repertoire_image",
                to="movie.movie",
            ),
        ),
    ]
