# Generated by Django 4.2.2 on 2024-01-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repertoire", "0002_repertoire_movie_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repertoire",
            name="movie_image",
        ),
        migrations.AddField(
            model_name="repertoire",
            name="movie_image_path",
            field=models.ImageField(
                blank=True, null=True, upload_to="repertoire_movie_images/"
            ),
        ),
    ]
