# Generated by Django 4.2.2 on 2024-01-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repertoire", "0003_remove_repertoire_movie_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repertoire",
            name="movie_image_path",
            field=models.ImageField(blank=True, null=True, upload_to="movie_images/"),
        ),
    ]
