# Generated by Django 4.2.2 on 2024-01-02 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repertoire", "0004_alter_repertoire_movie_image_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repertoire",
            name="movie_image_path",
        ),
    ]
