# Generated by Django 4.2.2 on 2024-01-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="movie_images/"),
        ),
    ]
